# Generated by Django 4.1.6 on 2023-02-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
